export const options = [
  { value: "SPRING", label: "Spring" },
  { value: "C", label: "C" },
  { value: "CPP", label: "Cpp" },
  { value: "JS", label: "JavaScript" },
  { value: "REACT", label: "React" },
  { value: "NODEJS", label: "NodeJS" },
  { value: "PYTHON", label: "Python" },
  { value: "DJANGO", label: "Django" },
  { value: "FLASK", label: "Flask" },
  { value: "GO", label: "Go" },
  { value: "SWIFT", label: "Swift" },
  { value: "ANGULAR", label: "Angular" },
  { value: "JAVA", label: "Java" },
  { value: "FLUTTER", label: "Flutter" },
  { value: "DOCKER", label: "Docker" },
  { value: "RUBY", label: "Ruby" },
  { value: "HTML", label: "HTML" },
  { value: "CSS", label: "CSS" },
  { value: "MYSQL", label: "MySQL" },
];
